import Card from '@/components/Card'
import HeadingWithParagraph from '@/components/HeadingWithParagraph'
import { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
  title: 'Car Page',
  description: 'Generated by Ali Allam',
}

const CarPage = () => {
  const cars = [1,2,3,4,5,6,7,8,9,10]
  return (
    <section className="py-5 md:py-10">
      <div className="container max-w-[1140px]">
        <HeadingWithParagraph
        heading="Luxury & Sports Car Rental"
        paragraph="We Offer High-End New Cars, Full option Vehicles."
        />

        <div className="grid grid-cols-[repeat(auto-fill,minmax(250px,300px))] justify-center gap-4">
          {cars.map((car,i)=><Card
          key={i}
          title="Testing"
          description="testing"
          src="/test.webp"
          href={`/car/${i}`}
          />)}
        </div>


      </div>
    </section>
  );
}

export default CarPage