import Card from "@/components/Card";
import HeadingWithParagraph from "@/components/HeadingWithParagraph";
import { Metadata } from "next";
import React from "react";
import CategoryCard from "./_components/CategoryCard";
import { getAllCategories } from "@/actions/category.actions";
import { ICategory } from "@/typings";
import Section from "@/components/Section";

export const metadata: Metadata = {
  title: "Category Page",
  description: "Generated by Ali Allam",
};

const CategoryPage = async () => {
  const categories = await getAllCategories();

  return (
    <Section>
      <div className="container max-w-[1140px]">
        <HeadingWithParagraph
          heading="Luxury & Sports Car Rental"
          paragraph="We Offer High-End New Cars, Full option Vehicles."
        />

        <div className="grid grid-cols-[repeat(auto-fill,minmax(250px,300px))] justify-center gap-4">
          {categories.map((category: ICategory, i: number) => (
            <CategoryCard category={category} key={i} />
          ))}
        </div>
      </div>
    </Section>
  );
};

export default CategoryPage;
