import Card from "@/components/Card";
import HeadingWithParagraph from "@/components/HeadingWithParagraph";
import { Metadata } from "next";
import React from "react";
import CategoryCard from "./_components/CategoryCard";
import { getAllCategories } from "@/actions/category.actions";
import { ICategory, SearchParamProps } from "@/typings";
import Section from "@/components/Section";
import { ApiFeatures } from "@/lib/utils";
import Pagination from "@/components/Pagination";

export const metadata: Metadata = {
  title: "Category Page",
  description: "Generated by Ali Allam",
};

const CategoryPage = async ({ searchParams }: SearchParamProps) => {
  const x = ApiFeatures(searchParams);
  const categories = await getAllCategories(x);

  return (
    <section
      className="py-10 px-5 min-h-screen mt-20
     bg-[url(https://purepng.com/public/uploads/large/purepng.com-ferrari-488-gtb-red-carcarferrarivehicletransport-9615246654455whpm.png),_url(https://wallpapers.com/images/hd/white-luxury-sports-car-95mu1ojxaty943fq.png)]
     bg-[position:top_5rem_right_-15rem,_bottom_1rem_left_-12rem]
     md:bg-[position:top_5rem_right_-10rem,_bottom_1rem_left_-8rem] 
      bg-no-repeat
      bg-[length:368px_368px]
    "
    >
      <div className="container max-w-[1140px]">
        <HeadingWithParagraph
          heading="Luxury & Sports Car Rental"
          paragraph="We Offer High-End New Cars, Full option Vehicles."
        />

        <div className="grid grid-cols-[repeat(auto-fill,minmax(250px,300px))] justify-center gap-4">
          {categories.results.map((category: ICategory, i: number) => (
            <CategoryCard category={category} key={i} />
          ))}
        </div>

        <Pagination totalPages={categories.totalPages} page={categories.page} />
      </div>
    </section>
  );
};

export default CategoryPage;
