import HeadingWithParagraph from "@/components/HeadingWithParagraph";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import BrandCard from "./_components/BrandCard";

export const metadata: Metadata = {
  title: "Brand Page",
  description: "Generated by Ali Allam",
};

export const brandsData = [
  {
    name: "lamborghini",
    imageUrl:
      "https://superiorrental.ae/wp-content/uploads/2020/04/580b585b2edbce24c47b2c8c-263x300.png",
  },
  {
    name: "ferrari",
    imageUrl:
      "https://ios.tahastore.ly/wp-content/uploads/2020/08/scuderia-ferrari-logo-800x1050-1-e1596686694886.png",
  },
  {
    name: "maserati",
    imageUrl:
      "https://superiorrental.ae/wp-content/uploads/2020/04/580b57fcd9996e24bc43c48f-300x169.png",
  },
  {
    name: "bentley",
    imageUrl:
      "https://superiorrental.ae/wp-content/uploads/2020/04/580b57fcd9996e24bc43c46c-e1588197827577-300x172.png",
  },
  {
    name: "rolls royce",
    imageUrl:
      "https://superiorrental.ae/wp-content/uploads/2020/04/580b57fcd9996e24bc43c4a0-300x300.png",
  },
  {
    name: "mclaren",
    imageUrl:
      "https://superiorrental.ae/wp-content/uploads/2020/04/580b57fcd9996e24bc43c492-1-e1588196988333-300x56.png",
  },
  {
    name: "porsche",
    imageUrl: "https://superiorrental.ae/wp-content/uploads/2020/04/10.png",
  },
  {
    name: "tesla",
    imageUrl: "https://1000logos.net/wp-content/uploads/2018/02/Logo-Tesla.jpg",
  },
  {
    name: "mercedes",
    imageUrl:
      "https://superiorrental.ae/wp-content/uploads/2020/04/580b57fcd9996e24bc43c493-e1588197984559-300x181.png",
  },
];

const BrandPage = () => {
  return (
    <section className="py-5 md:py-10">
      <div className="container max-w-[1140px]">
        <HeadingWithParagraph
          heading="Brands Page"
          paragraph="Here You Can Find Whatever You Want Just Take A Look"
        />
        <div className="grid grid-cols-[repeat(auto-fill,minmax(250px,300px))] justify-center gap-4 mt-8">
          {brandsData.map((brand, i) => (
            <Link href={`brand/${i}`} key={i}>
              <BrandCard brand={brand} />
            </Link>
          ))}
        </div>
      </div>
    </section>
  );
};

export default BrandPage;
