import type { Metadata } from "next";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import IconsContainer from "@/components/iconsConatiner";

export const metadata: Metadata = {
  title: "Car Rental",
  description: "Generated by Ali Allam",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <IconsContainer />
        <Footer />
      </body>
    </html>
  );
}
